version: "3.3"
services:
  db:
    image: mysql:8
    container_name: j_db
    ports:
      - "53306:3306"
    environment:
      MYSQL_DATABASE: "j_db"
      MYSQL_USER: "j_user"
      MYSQL_PASSWORD: "j_password"
      MYSQL_ROOT_PASSWORD: "rootpass"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci