# Generated by Django 3.2.9 on 2022-01-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='상품명')),
                ('price', models.PositiveIntegerField(verbose_name='가격(원)')),
                ('image', models.ImageField(upload_to='product/', verbose_name='사진')),
                ('description', models.TextField(verbose_name='상품설명')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
