# Generated by Django 3.2.9 on 2022-01-31 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_productoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='구매유저')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(max_length=200, null=True, verbose_name='입점사'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='구매수량')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='구매상품')),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productoption', verbose_name='구매상품의 옵션')),
            ],
            options={
                'db_table': 'orderItem',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='구매수량')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='구매상품')),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productoption', verbose_name='구매상품의 옵션')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='구매유저')),
            ],
            options={
                'db_table': 'cartItem',
            },
        ),
    ]
